service: video-process-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  timeout: 300
  memorySize: 3008
  region: ${file(./config.json):REGION}
  lambdaHashingVersion: 20201221

  environment:
    REGION: ${file(./config.json):REGION}
    S3_UPLOADS_BUCKET_NAME: ${file(./config.json):S3_UPLOADS_BUCKET_NAME}
    S3_KEYFRAME_BUCKET_NAME: ${file(./config.json):S3_KEYFRAME_BUCKET_NAME}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.S3_UPLOADS_BUCKET_NAME}/*"
        - "arn:aws:s3:::${self:provider.environment.S3_KEYFRAME_BUCKET_NAME}/*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.S3_UPLOADS_BUCKET_NAME}"
        - "arn:aws:s3:::${self:provider.environment.S3_KEYFRAME_BUCKET_NAME}"

functions:
  file-upload:
    handler: handlers/upload.handler
    environment:
      file_s3_bucket_name: ${self:provider.environment.S3_UPLOADS_BUCKET_NAME}
    events:
      - http:
          path: upload
          method: post
          cors: true
  get-video-list:
    handler: handlers/list.get_video_list_handler
    environment:
      keyframe_s3_bucket_name: ${self:provider.environment.S3_KEYFRAME_BUCKET_NAME}
    events:
      - http:
          path: list
          method: get
          cors: true
  get-keyframe-list:
    handler: handlers/list.get_keyframe_list_handler
    environment:
      keyframe_s3_bucket_name: ${self:provider.environment.S3_KEYFRAME_BUCKET_NAME}
    events:
      - http:
          path: list/{key}
          method: get
          cors: true
  extract-keyframe:
    handler: handlers/extract.handler
    environment:
      file_s3_bucket_name: ${self:provider.environment.S3_UPLOADS_BUCKET_NAME}
      keyframe_s3_bucket_name: ${self:provider.environment.S3_KEYFRAME_BUCKET_NAME}
    events:
      - s3:
          bucket: ${self:provider.environment.S3_UPLOADS_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .mp4
          existing: true
    layers:
      - { Ref: FfmpegLambdaLayer }
  detect-keyframe:
    handler: handlers/detect.handler
    environment:
      keyframe_s3_bucket_name: ${self:provider.environment.S3_KEYFRAME_BUCKET_NAME}
    events:
      - s3:
          bucket: ${self:provider.environment.S3_KEYFRAME_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .jpg
          existing: true

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_UPLOADS_BUCKET_NAME}
    KeyFrameResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_KEYFRAME_BUCKET_NAME}

layers:
  ffmpeg:
    path: layer

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - "multipart/form-data"
